apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev-namespace
---
kind: Pod
apiVersion: v1
metadata:
  name: dev-app
  namespace: dev
  labels:
    app: dev-app
spec:
  containers:
  - name: dev-app
    image: hashicorp/http-echo:latest
    args:
    - "-text=dev-app is running!"
---
kind: Service
apiVersion: v1
metadata:
  name: dev-app-service
  namespace: dev
spec:
  selector:
    app: dev-app
  ports:
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/dev"
        backend:
          service:
            name: dev-app-service
            port:
              number: 5678
---
#https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/04-deny-traffic-from-other-namespaces.md
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: dev
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}