kind: Pod
apiVersion: v1
metadata:
  name: wbdb
  labels:
    app: webbooks
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
      protocol: TCP
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "md5"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_DB
      value: "db_webbooks"
    volumeMounts:
    - name: init-script
      mountPath: /docker-entrypoint-initdb.d/db.sql
      subPath: data.sql
    - name: webbooks-vol
      mountPath: /var/lib/postgresql/data
  volumes:
    - name: init-script
      configMap:
        name: init-script
        items:
        - key: data.sql
          path: ./build/webbooks/src/main/resources/data.sql
    - name: webbooks-vol
      persistentVolumeClaim:
        claimName: webbooks-pvc
  restartPolicy: Always

---

kind: Pod
apiVersion: v1
metadata:
  name: webbooks
  labels:
    app: webbooks
spec:
  containers:
  - name: webbooks
    image: webbooks:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort:  8080
      name:  http

---

kind: Service
apiVersion: v1
metadata:
  name: webbooks-service
spec:
  selector:
    app: webbooks
  ports:
  - port: 8080

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: webbooks-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/wbdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webbooks-pvc
  namespace: default
  labels:
    app: webbooks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi